MovieApp/Models/Category.cs
namespace MovieApp.Models
{
    public class Category
    {
        public int  Id { get; set; }
        public string Name { get; set; }
    }
}

MovieApp/Models/ErrorViewModel.cs
using System;

namespace MovieApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieApp/Models/Movie.cs
namespace MovieApp.Models
{
    public class Movie
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public string shortDescription { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int CategoryId { get; set; }
    }
}

MovieApp/Models/MovieCategoryAssoc.cs
using System.Collections.Generic;

namespace MovieApp.Models
{
    public class MovieCategoryAssoc
    {
        public Movie Movie { get; set; }
        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

MovieApp/Models/Repository.cs
using System.Collections.Generic;
using System.Linq;

namespace MovieApp.Models
{
    public static class Repository
    {
        private static List<Movie> _movies = null;

        static Repository()
        {
            _movies = new List<Movie>()
            {
                new Movie()
                {
                    Id = 1, Name = "The Godfather", 
                    Description = "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
                    ImageUrl = "1.jpg"
                },
                new Movie(){ 
                    Id = 2, Name = "The Shawshank Redemption",
                    Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                    ImageUrl = "2.jpg"},
                new Movie(){ 
                    Id = 3, Name = "The Godfather Part II",
                    Description = "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
                    ImageUrl = "3.jpg"},
                new Movie(){ 
                    Id = 4, Name = "Inception",
                    Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
                    ImageUrl = "4.jpg"},
                new Movie(){ 
                    Id = 5, Name = "Fight Club",
                    Description = "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
                    ImageUrl = "5.jpg"},
                new Movie(){ 
                    Id = 6, Name = "The Dark Knight",
                    Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    ImageUrl = "6.jpg"},
                new Movie(){ 
                    Id = 7, Name = "12 Angry Men",
                    Description = "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.",
                    ImageUrl = "7.jpg"},
                new Movie(){ 
                    Id = 8, Name = "The Lord of the Rings: The Fellowship of the Ring",
                    Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                    ImageUrl = "8.jpg"},
                new Movie(){ 
                    Id = 9, Name = "The Matrix",
                    Description = "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
                    ImageUrl = "9.jpg"},
                new Movie(){ 
                    Id = 10, Name = "Se7en",
                    Description = "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
                    ImageUrl = "10.jpg"}
            };
        }

        public static List<Movie> GetMovies()
        {
            return _movies;
        }

        public static void AddMovie(Movie movie)
        {
            _movies.Add(movie);
        }

        public static Movie GetMovieById(int id)
        {
            return _movies.FirstOrDefault(i => i.Id == id);
        }
    }
}

MovieApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieApp.Data;
using MovieApp.Models;

namespace MovieApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [HttpGet]
        public IActionResult Index(int? id)
        {
            var movies = MovieRepository.GetMovies();
            if (id != null)
            {
                movies = movies.Where(i => i.CategoryId == id).ToList();
            }
            return View(movies);
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            return View(MovieRepository.GetMovieById(id));
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

MovieApp/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        
        
        public IActionResult Create()
        {
            return View();
        }
        
        public IActionResult List()
        {
            return View();
        }
    }
}

MovieApp/ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;

namespace MovieApp.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if(RouteData?.Values["action"]?.ToString() == "Index")
            {
                ViewBag.SelectedCategory = RouteData?.Values["id"];
            }
            
            return View(CategoryRepository.GetCategories());
        }
    }
}

MovieApp/Views/Home/Contact.cshtml
<h1>Home/Contact</h1>

MovieApp/Views/Home/Details.cshtml
@model Movie

<div class="row">
    <div class="col-md-3">
        @*@Html.Partial("_menu", Model.Categories)*@
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        <div class="card mb-3">

            <div class="card-body">
                <div class="row no-gutter">
                    <div class="col-md-4">
                        <img src="~/img/@Model.ImageUrl" alt="@Model.Description" class="card-img">
                    </div>
                    <div class="col-md-8">
                        
                        <h5 class="card-title">
                            <a asp-action="Details" asp-controller="Home" asp-route-id="@Model.Id">  @Model.Name</a> 
                        </h5>
                        <p class="card-text">
                            @Html.Raw(Model.Description)
                        </p>
                        <p class="card-text">
                            <small class="text-muted">3 days ago</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MovieApp/Views/Home/Index.cshtml
@model IEnumerable<Movie>

<div class="row">
    <div class="col-md-3">
        @*@Html.Partial("_menu", Model.Categories)*@
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        <partial name="_movies" model="Model"/>
    </div>
</div>

MovieApp/Views/Home/_movies.cshtml
@model IEnumerable<Movie>

@foreach (var movie in Model)
{
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="~/img/@movie.ImageUrl" alt="@movie.shortDescription" class="card-img"/>
            </div>
        
            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title">
                        <a asp-action="Details" asp-controller="Home" asp-route-id="@movie.Id">@movie.Name</a>
                    </h5>
                    <p class="card-text">
                        @movie.shortDescription
                    </p>
                    <p class="card-text">
                        <small class="text-muted">3 days ago</small>
                    </p>
                </div>
            </div>

        </div>
    </div>

}
    

MovieApp/Views/Movie/Create.cshtml
<h1>Movie/Create</h1>

MovieApp/Views/Movie/Index.cshtml
<h1>Movie/Index</h1>

MovieApp/Views/Movie/List.cshtml
<h1>Movie/List</h1>

MovieApp/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>


<a href="/"class="list-group-item list-group-item-action ">Categories</a>
@foreach (var category in Model)
{
    <div class="list-group">
        <a asp-controller="Home" asp-action="Index" asp-route-id="@category.Id" class="list-group-item list-group-item-action @(ViewBag.SelectedCategory == category.Id.ToString() ? "active" : "")">@category.Name</a>
    </div>
}

MovieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge">   
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="css/style.css"/>
    <title>Movie App</title>
</head>

<body>

<header>
    @Html.Partial("_navbar")
</header>

<main>
    <div class="container mt-4">
        @RenderBody()
    </div>
</main>

<footer>
    @Html.Partial("_footer")
</footer>

</body>
</html>

MovieApp/Views/Shared/_footer.cshtml
<div class="footer py-3 mt-3"> 
    <div class="container">
        <span class="text-muted">
            Place footer content here
        </span>
    </div>
</div>

MovieApp/Views/Shared/_menu.cshtml
@model IEnumerable<Category>


@foreach (var category in Model)
{
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action ">@category.Name</a>
    </div>
}

MovieApp/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
        <a href="/" class="navbar-brand">Movie App</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/login" class="nav-link">Login</a>
            </li>
            <li class="nav-item">
                <a href="/register" class="nav-link">Register</a>
            </li>
        </ul>
    </div>

</nav>